development:
  adapter: postgresql
  encoding: unicode
  database: okwork_development
  username: okuyamakenta
  host: localhost
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: okwork_test
  username: okuyamakenta
  host: localhost
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: okwork_production
  username: okwork
  password: kenta245502
  host: 127.0.0.1
  pool: 5